Repository nats-io/nats.net, pull requests merged in 2024-04, with the labels that each got.

#459 Object store metadata fix
  src/NATS.Client.ObjectStore/Models/ObjectMetadata.cs
  tests/NATS.Client.ObjectStore.Tests/CompatTest.cs
Labels: bug

#454 Add client certificate chain support and SSL context generation
  src/NATS.Client.Core/Internal/SslStreamConnection.cs
  src/NATS.Client.Core/Internal/TlsCerts.cs
  src/NATS.Client.Core/NatsTlsOpts.cs
  tests/NATS.Client.Core.Tests/NATS.Client.Core.Tests.csproj
  tests/NATS.Client.Core.Tests/TlsCertsTest.cs
  tests/NATS.Client.Core.Tests/resources/certs/ca-cert.pem
  tests/NATS.Client.Core.Tests/resources/certs/chainedclient-cert.pem
  tests/NATS.Client.Core.Tests/resources/certs/chainedclient-key.pem
  tests/NATS.Client.Core.Tests/resources/certs/client-cert.pem
  tests/NATS.Client.Core.Tests/resources/certs/client-key.pem
  tests/NATS.Client.Core.Tests/resources/certs/generate.sh
  tests/NATS.Client.Core.Tests/resources/certs/intermediate01-cert.pem
  tests/NATS.Client.Core.Tests/resources/certs/intermediate01-key.pem
  tests/NATS.Client.Core.Tests/resources/certs/intermediate02-cert.pem
  tests/NATS.Client.Core.Tests/resources/certs/intermediate02-key.pem
  tests/NATS.Client.Core.Tests/resources/certs/leafclient-cert.pem
  tests/NATS.Client.Core.Tests/resources/certs/leafclient-key.pem
  tests/NATS.Client.Core.Tests/resources/certs/server-cert.pem
  tests/NATS.Client.Core.Tests/resources/certs/server-key.pem
Labels: enhancement

#455 Deserialize empty payloads
  src/NATS.Client.Core/INatsSerialize.cs
  src/NATS.Client.Core/NatsMsg.cs
  src/NATS.Client.JetStream/Internal/NatsJSErrorAwareJsonSerializer.cs
  src/NATS.Client.Serializers.Json/NatsJsonSerializer.cs
  tests/NATS.Client.Core.Tests/SerializerTest.cs
Labels: bug, breaking

#433 Update NATS.Client.Hosting package as NATS.Extensions.Microsoft.DependencyInjection
  NATS.Client.sln
  src/NATS.Extensions.Microsoft.DependencyInjection/NATS.Extensions.Microsoft.DependencyInjection.csproj
  src/NATS.Extensions.Microsoft.DependencyInjection/NatsBuilder.cs
  src/NATS.Extensions.Microsoft.DependencyInjection/NatsHostingExtensions.cs
  tests/NATS.Extensions.Microsoft.DependencyInjection.Tests/MyJsonContext.cs
  tests/NATS.Extensions.Microsoft.DependencyInjection.Tests/NATS.Extensions.Microsoft.DependencyInjection.Tests.csproj
  tests/NATS.Extensions.Microsoft.DependencyInjection.Tests/NatsHostingExtensionsTests.cs
Labels: enhancement

#481 Validate KV keys
  src/NATS.Client.KeyValueStore/INatsKVStore.cs
  src/NATS.Client.KeyValueStore/NatsKVContext.cs
  src/NATS.Client.KeyValueStore/NatsKVStore.cs
  tests/NATS.Client.Core.Tests/TlsClientTest.cs
  tests/NATS.Client.KeyValueStore.Tests/KeyValueStoreTest.cs
Labels: breaking
